### ISSUE TITLE
Management of resources through a subsite

### ISSUE THREAD

**Issue by kilichenko-pixida** [geosolutions-it/geonode-subsites#43]
In order to enable resource management both the setting 
`SUBSITE_READ_ONLY = False` was added and in the admin panel 
"Contributors can add resources" was checked. 

However, (as also confirmed by @ridoo) dataset upload doesn't work. The request goes to
`<subsite_name>/api/v2/uploads/upload` which of course returns 404.

**Comment by mattiagiupponi** [comment]
The initial idea was to keep the upload common (so we dont need to override the endpoint for it) and then is the customization of the subsite/resource that place the resource in a specific subsite.

**Comment by ridoo** [comment]
@mattiagiupponi I am fine with that decision .. however, do we have to configure the `geonode-mapstore-client` somehow so that `Upload Dataset` points to the main catalogue's upload page? Now it just  points to `http://172.18.0.1:8001/<subsite>/catalogue/#/upload/dataset` (the same for all other entries in the `Add Resource` menu. Probably the upload URLs have to be excluded by default in the hookset?

**Comment by mattiagiupponi** [comment]
hi @ridoo 
You can for sure use the dataset_upload_url, but this it means that the we have to add login in geonode (which i would avoid). Probably we never notice the issue since we kept the subsite in read_only for our POCs
I would approach in two ways in case:
- Override the upload URL (like we did for the others) and have an upload url per subsite
- Override the upload URL and let it redrect to the default upload URL

**Comment by ridoo** [comment]
Covered actually by https://github.com/Thuenen-GeoNode-Development/thuenen_atlas/issues/55

**Comment by vineetasharma105** [comment]
@kilichenko-pixida : Hi , This is issue is resolved and may be closed .
